# Generated by Django 3.2.4 on 2021-06-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='start',
            new_name='stars',
        ),
    ]
